name: Build & Deploy
on: push
permissions:
  contents: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Deps
        run: |
          sudo apt-get install libcmark-dev curl
          curl -L https://codeberg.org/0ref/jelly/releases/download/0.1.0/jelly-linux-x86_64 --output jelly
          curl -L https://github.com/wilsonzlin/minify-html/releases/download/v0.15.0/minhtml-0.15.0-x86_64-unknown-linux-gnu --output minhtml
          chmod +x ./jelly
          chmod +x ./minhtml
          ./jelly -i src -o build
          ./minhtml --keep-closing-tags --minify-css --minify-js \
            --keep-spaces-between-attributes \
            --keep-input-type-text-attr \
            --keep-html-and-head-opening-tags \
            $(find build/ -type f -name "*.html")

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
