name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Deploy-To-Branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm install
          npm test
          echo "Beforeeeeeeeee"
          ls
          echo "Afterrrrrrrrrr"
          rm -r clean.sh LICENSE content/ node_modules/ .github/ *.json *.md *.js
          echo "Afterrrrrrrrrr"
          ls

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ./
